/**
 * Downtime Alert Email Template
 * Sends alert when site receives no pageviews for configured period
 */
import React from 'react';

import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Heading,
  Text,
  Hr,
  Link,
} from '@react-email/components';

export interface DowntimeEmailData {
  domain: string;
  lastPageviewTime: Date;
  thresholdMinutes: number;
  cooldownHours: number;
  dashboardUrl: string;
}

/**
 * Sanitize domain to prevent XSS
 */
function sanitize(str: string): string {
  return str
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
    .replace(/\//g, '&#x2F;');
}

/**
 * Format timestamp for display
 */
function formatTimestamp(date: Date): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
    timeZoneName: 'short',
  }).format(date);
}

/**
 * Downtime Alert Email Template
 */
export default function DowntimeEmail({
  domain,
  lastPageviewTime,
  thresholdMinutes,
  cooldownHours,
  dashboardUrl,
}: DowntimeEmailData) {
  const sanitizedDomain = sanitize(domain);
  const siteUrl = `https://${sanitizedDomain}`;

  return (
    <Html>
      <Head />
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>⚠️ Downtime Alert: {sanitizedDomain}</Heading>

          <Text style={text}>Hi there,</Text>

          <Text style={text}>
            Your site <strong>{sanitizedDomain}</strong> has not received any pageviews for{' '}
            <strong>{thresholdMinutes} minutes</strong>.
          </Text>

          <Section style={alertBox}>
            <table style={table}>
              <tbody>
                <tr>
                  <td style={tableCell}>
                    <strong>Last Pageview:</strong>
                  </td>
                  <td style={tableCell}>{formatTimestamp(lastPageviewTime)}</td>
                </tr>
                <tr>
                  <td style={tableCell}>
                    <strong>Alert Threshold:</strong>
                  </td>
                  <td style={tableCell}>{thresholdMinutes} minutes</td>
                </tr>
              </tbody>
            </table>
          </Section>

          <Text style={text}>This could indicate:</Text>

          <ul style={list}>
            <li style={listItem}>Site is down</li>
            <li style={listItem}>Tracking script is not loading</li>
            <li style={listItem}>DNS/hosting issue</li>
          </ul>

          <Hr style={hr} />

          <Text style={text}>
            <Link href={siteUrl} style={link}>
              Check your site →
            </Link>
          </Text>

          <Text style={text}>
            <Link href={dashboardUrl} style={link}>
              View dashboard →
            </Link>
          </Text>

          <Hr style={hr} />

          <Text style={text}>
            This alert will not fire again for <strong>{cooldownHours} hours</strong>.
          </Text>

          <Hr style={hr} />

          <Text style={footer}>Generated by My Analytics</Text>
        </Container>
      </Body>
    </Html>
  );
}

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
};

const h1 = {
  color: '#333',
  fontSize: '24px',
  fontWeight: 'bold',
  margin: '40px 0 20px',
  padding: '0 40px',
};

const text = {
  color: '#333',
  fontSize: '14px',
  lineHeight: '24px',
  padding: '0 40px',
};

const alertBox = {
  backgroundColor: '#f8d7da',
  border: '1px solid #dc3545',
  borderRadius: '4px',
  padding: '16px',
  margin: '20px 40px',
};

const table = {
  width: '100%',
};

const tableCell = {
  color: '#333',
  fontSize: '14px',
  lineHeight: '24px',
  padding: '4px 0',
};

const list = {
  padding: '0 40px 0 60px',
  margin: '10px 0',
};

const listItem = {
  color: '#333',
  fontSize: '14px',
  lineHeight: '24px',
  marginBottom: '8px',
};

const hr = {
  borderColor: '#e6ebf1',
  margin: '20px 0',
};

const link = {
  color: '#556cd6',
  textDecoration: 'underline',
};

const footer = {
  color: '#8898aa',
  fontSize: '12px',
  lineHeight: '16px',
  padding: '0 40px',
};
