/**
 * Traffic Spike Alert Email Template
 * Sends alert when pageviews exceed threshold
 */
import React from 'react';

import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Heading,
  Text,
  Hr,
  Link,
} from '@react-email/components';

export interface TrafficSpikeEmailData {
  domain: string;
  currentTraffic: number;
  threshold: number;
  cooldownHours: number;
  dashboardUrl: string;
}

/**
 * Sanitize domain to prevent XSS
 */
function sanitize(str: string): string {
  return str
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
    .replace(/\//g, '&#x2F;');
}

/**
 * Traffic Spike Alert Email Template
 */
export default function TrafficSpikeEmail({
  domain,
  currentTraffic,
  threshold,
  cooldownHours,
  dashboardUrl,
}: TrafficSpikeEmailData) {
  const sanitizedDomain = sanitize(domain);

  return (
    <Html>
      <Head />
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>🚀 Traffic Spike Alert: {sanitizedDomain}</Heading>

          <Text style={text}>Hi there,</Text>

          <Text style={text}>
            Your site <strong>{sanitizedDomain}</strong> is experiencing a traffic spike!
          </Text>

          <Section style={alertBox}>
            <table style={table}>
              <tbody>
                <tr>
                  <td style={tableCell}>
                    <strong>Current Traffic:</strong>
                  </td>
                  <td style={tableCell}>{currentTraffic.toLocaleString()} pageviews in the last hour</td>
                </tr>
                <tr>
                  <td style={tableCell}>
                    <strong>Alert Threshold:</strong>
                  </td>
                  <td style={tableCell}>{threshold.toLocaleString()} pageviews per hour</td>
                </tr>
              </tbody>
            </table>
          </Section>

          <Text style={text}>
            This alert will not fire again for <strong>{cooldownHours} hours</strong> to prevent spam.
          </Text>

          <Hr style={hr} />

          <Text style={text}>
            <Link href={dashboardUrl} style={link}>
              View real-time data →
            </Link>
          </Text>

          <Hr style={hr} />

          <Text style={footer}>Generated by My Analytics</Text>
        </Container>
      </Body>
    </Html>
  );
}

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
};

const h1 = {
  color: '#333',
  fontSize: '24px',
  fontWeight: 'bold',
  margin: '40px 0 20px',
  padding: '0 40px',
};

const text = {
  color: '#333',
  fontSize: '14px',
  lineHeight: '24px',
  padding: '0 40px',
};

const alertBox = {
  backgroundColor: '#fff3cd',
  border: '1px solid #ffc107',
  borderRadius: '4px',
  padding: '16px',
  margin: '20px 40px',
};

const table = {
  width: '100%',
};

const tableCell = {
  color: '#333',
  fontSize: '14px',
  lineHeight: '24px',
  padding: '4px 0',
};

const hr = {
  borderColor: '#e6ebf1',
  margin: '20px 0',
};

const link = {
  color: '#556cd6',
  textDecoration: 'underline',
};

const footer = {
  color: '#8898aa',
  fontSize: '12px',
  lineHeight: '16px',
  padding: '0 40px',
};
